name: build

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: welcome message
              run: |
                echo " This is just a CI practice"
                ls -ltra
                cat README.md 
            - name: Generate ASCII Artwork
              run: |
                sudo apt-get install cowsay -y
                cowsay -f dragon "RAWR LIIKE A DRAGON!" >> dragon.txt 
                cat dragon.txt   

            

 
