name: build

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: welcome message
              run: echo " This is just a CI practice"

            - name: list files and permissions
              run: ls -l

            - name: Read file
              run: cat README.md  

 
