name: build

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: welcome message
              run: |
                echo " This is just a CI practice"
                ls -ltra
                cat README.md 
            - name: Generate ASCII Artwork
              run: |
                chmod +x ascii-script
                ./ascii-script.sh

            

 
