name: Changesets

on:
  pull_request:
    branches: [stage, main]

jobs:
  ensure-versioning-pr-merged:
    name: Ensure versioning PR has been merged
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Only allow merging if we have no changesets (meaning the versioning PR has been merged)
        run: |
          if [ -n "$(ls -A .changeset | grep .md)" ]; then
            echo "Changesets found in .changeset folder. Please review and merge the versioning PR first."
            exit 1
          fi